
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('menu').truncate()
    .then(function () {
      // Inserts seed entries
      return knex('menu').insert([
        //{id:, item:'', price:"$",type:'',description:'', restaurant_id:},
        //THE BITTER BAR
        {id: 1, item: 'Tin Man', price: '$7',type: 'cocktail',description: 'Bourbon, elderflower, lemon, ginger ale', restaurant_id:1},
        {id:2, item:'Kiss The Sky', price:"$7", type: 'cocktail',description: 'Gin, ginger liqeur, lavender syrup, lemon', restaurant_id:1},
        {id: 3, item: 'Blue Velvet', price: '$7',type: 'cocktail',description: 'Vodka, creme de violette, lemon, orgeat', restaurant_id:1},
        {id:4, item:'Silver Coin', price:"$7",type: 'cocktail',description: 'Blanco, tequila, triple sec, lime', restaurant_id:1},
        {id:5, item:'Bouldervardier', price:"$7",type:'cocktail',description: 'Bourbon, aperol, cocchi torino', restaurant_id:1},
        {id:6, item:'Lager & Orion cans', price:"$5",type:'beer',description: '', restaurant_id:1},
        {id:7, item:'House Wine', price:"$5",type:'wine',description:'', restaurant_id:1},
        {id:8, item:'Rosé Brut', price:"$5",type:'wine',description:'', restaurant_id:1},
        //T/ACO
        {id:9, item:'Draft Beer', price:"$3",type:'beer',description:'', restaurant_id:2},
        {id:10, item:'Margarita', price:"$4",type:'cocktail',description:'', restaurant_id:2},
        {id:11, item:'Silver Shot', price:"$5",type:'shot',description:'', restaurant_id:2},
        {id:12, item:'Juicy Margarita', price:"$6",type:'cocktail',description:'', restaurant_id:2},
        {id:13, item:'Street taco', price:"$2",type:'food',description:'', restaurant_id:2},
        //HAPPA
        //{id:, item:'', price:"$",type:'',description:'', restaurant_id:},
        {id:14, item:'Chilled fruit infused sake', price:"$7",type:'sake',description:'Mango Nigori or Raspberry Sake (10oz)', restaurant_id:3},
        {id:15, item:'Hot sake', price:"$6",type:'sake',description:'Gekkeikan, Purple Haze, Vanilla Sake (10oz)', restaurant_id:3},
        {id:16, item:'G-spot', price:"$7",type:'cocktail',description:'Raspberry Vodka, Hapa infused raspberry sake, ginger ale', restaurant_id:3},
        {id:17, item:'The Jasmine ', price:"$7",type:'cocktail',description:'Gin, Aperol, jasmine and lemon with a touch of spritz', restaurant_id:3},
        {id:18, item:'Clouds of Paradise', price:"$7",type:'cocktail',description:'Jameson Caskmates, Hapa infused mango nigori, lemon,touch of coconut', restaurant_id:3},
        {id:19, item:'Island Flirt', price:"$7",type:'cocktail',description:'White rum, sweet and tart passionfruit puree, lime, dash of bitters', restaurant_id:3},
        {id:20, item:'Soji Blossom', price:"$7",type:'cocktail',description:'Soju, hibiscus, lemon, seltzer', restaurant_id:3},
        {id:21, item:'Ume Margarita', price:"$7",type:'cocktail',description:'Espolon Blanco tequila, salted plum, lime ', restaurant_id:3},
        {id:22, item:'Sake Bomb', price:"$9.5",type:'sake',description:'21 oz Kirin and large hot sake. (+1 for Asahi and Sapporo)', restaurant_id:3},
        {id:23, item:'Sake Drop', price:"$11",type:'sake',description:'21 oz Kirin and a large, chilled mango infused nigori or raspberry infused sake.', restaurant_id:3},
        {id:24, item:'Well Drinks', price:"$7",type:'cocktail',description:'', restaurant_id:3},
        {id:25, item:'House Wine' , price:"$6",type:'wine',description:'', restaurant_id:3},
        {id:26, item:'Asparagus Maki', price:"2 for $8",type:'food',description:'Asparagus roll', restaurant_id:3},
        {id:27, item:'Avacado Roll', price:"2 for $8",type:'food',description:'', restaurant_id:3},
        {id:28, item:'Cucumber Avacado Roll', price:"2 for $8",type:'food',description:'', restaurant_id:3},
        {id:29, item:'Shink Maki', price:"2 for $8",type:'food',description:'Pickled radish roll', restaurant_id:3},
        {id:30, item:'Ume Shiso Maki', price:"2 for $8",type:'food',description:'plum and Shiso leaf', restaurant_id:3},
        {id:31, item:'Tempora Asparagus Roll', price:"2 for $8",type:'food',description:'', restaurant_id:3}, 
        {id:32, item:'Vegtable Roll', price:"2 for $8",type:'',description:' Avocado, cucumber, takuan, shiitake mushrooms, kanpyo and gobo', restaurant_id:3},
        {id:33, item:'California Roll', price:"2 for $10",type:'food',description:'California mix, avocado, and cucumber ', restaurant_id:3},
        {id:34, item:'LA Roll', price:"2 for $10",type:'food',description:'Shrimp, avocado, cucumber', restaurant_id:3},
        {id:35, item:'Pittsburgh Roll', price:"2 for $10",type:'food',description:'Fresh salmon, cucumber and cream cheese', restaurant_id:3},
        {id:36, item:'Salmon Avacado Roll', price:"2 for $10",type:'food',description:'', restaurant_id:3},
        {id:37, item:'Shake Maki', price:"2 for $10",type:'food',description:'Salmon roll', restaurant_id:3},
        {id:38, item:'Spicy Salmon', price:"2 for $10",type:'food',description:'Spicy Salmon and cucumber', restaurant_id:3},
        {id:39, item:'White Tuna Roll', price:"2 for $10",type:'food',description:'Albacore tuna, ginger and scallions', restaurant_id:3},
        {id:40, item:'Miso Soup', price:"$3.75",type:'food',description:'Served with tofu, scallions, and wakame', restaurant_id:3},
        {id:41, item:'Edamame', price:"$4.5",type:'food',description:'Lightly salted soybeans', restaurant_id:3},
        {id:42, item:'Seasoned Edamame', price:"$5.5",type:'food',description:'Sautéed soybeans with Hapa’s spicy seasonings', restaurant_id:3},
        {id:43, item:'Magic Mushrooms', price:"$8",type:'food',description:'Avocado wrapped in salmon, broiled with Japanese aioli and sweet soy', restaurant_id:3},
        {id:44, item:'Shumai', price:"$5.5",type:'food',description:'Steamed shrimp dumplings', restaurant_id:3},
        {id:45, item:'Ginger Pork Gyoza', price:"$5.5",type:'food',description:"Hapa's pork potstickers served with a spicy soy sauce", restaurant_id:3},
        {id:46, item:'Vegetaable Gyoza', price:"$5.5",type:'food',description:"Hapa’s vegetable potstickers served with a spicy soy sauce", restaurant_id:3},
        {id:47, item:'Broiled Green Mussles', price:"$6.5",type:'food',description:'New Zealand green lipped mussels broiled in a Japanese aioli, drizzled with sweet soy•', restaurant_id:3},
        {id:48, item:'Agedashi Tofu', price:"$6",type:'food',description:'Traditional style tofu in a pool of dashi broth', restaurant_id:3},
        {id:49, item:'Vegetable Tempura', price:"$7.5",type:'food',description:'Seasonal vegetable tempura served with a dipping sauce', restaurant_id:3},
        {id:50, item:'Tempura Shrimp', price:"$2",type:'food',description:'One piece', restaurant_id:3},
        {id:51, item:'Wagyu Bao', price:"$9",type:'food',description:'Two steamed bao buns loaded up with sautéed Wagyu beef cucumber, pickled daikon and carrot and kimchi ', restaurant_id:3},
        {id:52, item:'Taro Poke', price:"$11",type:'food',description:' (Pronounced po-kay) Hawaiian style tuna or salmon poke over a seared taro cake, finished with cool cucumbers and yuzu sour cream•', restaurant_id:3},
        {id:53, item:'American Kobe Carpaccio', price:"$12",type:'food',description:'Black pepper seared Wagyu beef served with fresh jalapeños and jalapeño ponzu', restaurant_id:3},
        {id:54, item:'Spicy Tuna Nachos', price:"$10.95",type:'food',description:'Spicy tuna, fresh mango salsa, guacamole, and sour cream served with fresh tortilla chips and sweet soy', restaurant_id:3},
        {id:55, item:'Thai Style Chicken Skewers', price:"$6",type:'food',description:'All natural chicken skewers marinated with Thai seasonings, grilled over an open flame and topped with toasted shredded coconut•', restaurant_id:3},
        {id:56, item:'Monkey Brain', price:"$9",type:'food',description:'Sliced tempura avocado, spicy tuna, and California mix, drizzled with sriracha mayo and sweet soy, topped with green onions', restaurant_id:3},
        {id:57, item:'Hawaiin Calamari', price:"$8.25",type:'food',description:'Panko crusted calamari with a mango chili dipping sauce', restaurant_id:3},
        {id:58, item:'Happa Hawaiin Sliders', price:"$8.25",type:'food',description:'Four mini Kalua pork sandwiches on Hawaiian sweet rolls with Asian slaw and tomatoes•', restaurant_id:3},
        {id:59, item:'Hawaiian Kanpachi Crudo', price:"$14",type:'food',description:'7 pieces of kanpachi sashimi with kimchi furikake, chive oil, ponzu, jalapeño and mandarin orange', restaurant_id:3},
        {id:60, item:'Colorado Hamachi', price:"$14",type:'food',description:'7 pieces of hamachi sashimi served with fresh jalapeños, yuzu soy, and cilantro•', restaurant_id:3},
        {id:61, item:'Island Misa Ahi', price:"$14",type:'food',description:'7 pieces of maguro sashimi with wakame furikake, chive and miso sauce ', restaurant_id:3},
        {id:62, item:'Crispy Seared Ahi', price:"$12",type:'food',description:'5 pieces of fresh tuna encrusted with crushed Japanese rice crackers, seared and served with Asian slaw and sweet chili sauce', restaurant_id:3},
        {id:63, item:"Scotty's Salmon", price:"$14",type:'food',description:'7 pieces of salmon sashimi sprinkled with diced tomato, garlic, red onion, caper, basil and cilantro. Finished with olive oil and yuzu soy', restaurant_id:3},
        {id:64, item:'New Style Hapa Sashimi', price:"$12",type:'food',description:'5 pieces of assorted sashimi seared in a garlic olive oil with cilantro and ponzu', restaurant_id:3},
        ///CORK
        {id:65, item:'Cosmo or Lemon Drop', price:"$7.5",type:'cocktail',description:'', restaurant_id:4},
        {id:66, item:'House Martinin', price:"$7.7",type:'cocktail',description:'Svedka Vodka or Greenwalls Gin with olives or a twist', restaurant_id:4},
        {id:67, item:'Margarita', price:"$7.7",type:'cocktail',description:'Coin stlye made with agavales 100% Blue Agave Silver Tequila, Cointreau and fresh lime', restaurant_id:4},
        {id:68, item:'Wines', price:"$5",type:'wine',description:'Cabernet | Chardonnay | Sparkling', restaurant_id:4},
        {id:69, item:'Sangria', price:"$5",type:'cocktail',description:'Decadent Saint White & Red', restaurant_id:4},
        {id:70, item:'Well Drinks', price:"$5",type:'cocktails',description:'Svedka Vodka | Greenwalls Gin | Four Roses Bourbon | Agavales Tequila | Cane Run White Rum | Glen Moray Classic Scotch', restaurant_id:4},
        {id:71, item:'Draft Beer', price:"$4.9",type:'beer',description:'Bavik Super Pils | Deshutes Mirror Pond Pale | Post IPA | Wibby Lager', restaurant_id:4},
        {id:72, item:'Wedge', price:"$6.5",type:'food',description:'Blue cheese, diced tomatoes and bacon', restaurant_id:4},
        {id:73, item:'Ceasar Salad', price:"$5.8",type:'food',description:'Add grilled chicken for $3', restaurant_id:4},
        {id:74, item:'Artichoke', price:"$8.8",type:'food',description:'With curry mayonnaise', restaurant_id:4},
        {id:75, item:'House-made Waffle Potato Chipps', price:"$6.4",type:'food',description:'With creamy blue cheese and topped with arugala', restaurant_id:4},
        {id:76, item:'Nachos', price:"$7.4",type:'food',description:'With jack cheese, salsa, black beans, guacamole and sour cream', restaurant_id:4},
        {id:77, item:'La Quercia Organic Prociutto & Carr Valley Cheese Plate', price:"$9.5",type:'food',description:'', restaurant_id:4},
        {id:78, item:'Baked Stuffed Chille', price:"$4.8",type:'food',description:'With jack cheese, tomato-herb and corn salsa, sour cream and guacamole', restaurant_id:4},
        {id:79, item:'Chicken Enchilada', price:"$6.4",type:'food',description:'Backed in red chile with cheese, guacamole, and sour cream', restaurant_id:4}, 
        {id:80, item:'Fish & Chips', price:"$10.9",type:'food',description:'With tarta sauce and coleslaw', restaurant_id:4},
        {id:81, item:"Jim's Fish Tacos", price:"$14.6",type:'food',description:'With warm tortillas, salsa, guacamole and beans', restaurant_id:4},
        {id:82, item:"Green Chile & Aged WHite Chedder Mac'n Cheese", price:"$6.5",type:'food',description:'Add diced chicken or bacon for $3', restaurant_id:4},
        {id:83, item:'Grilled Fish Bowl', price:"$9.5",type:'food',description:'Fresh fish over Green rice and veggies with a coconut curry sauce', restaurant_id:4},
        {id:84, item:'Fresh Ahi Tuna Sandwitch', price:"$12.4",type:'food',description:'', restaurant_id:4},
        {id:85, item:'Smoked Chicken Quesadilla', price:"$4.5",type:'food',description:'', restaurant_id:4},
        {id:86, item:'Spicy Green Chile Cheeseburger', price:"$8.5",type:'food',description:'With fries', restaurant_id:4},
        {id:87, item:'Mud Pie Bites', price:"$5.9",type:'food',description:'', restaurant_id:4},
        //JAPANGO
        {id:88, item:'Sapporr Draft', price:"$4",type:'beer',description:'', restaurant_id:5},
        {id:89, item:'Small Hot Sake', price:"$5",type:'sake',description:'sake', restaurant_id:5},
        {id:90, item:'House Wine', price:"$7",type:'wine',description:'', restaurant_id:5},
        {id:91, item:'Well Cocktails', price:"$7",type:'cocktail',description:'', restaurant_id:5},
        {id:92, item:'Cold Sake', price:"$8",type:'sake',description:'', restaurant_id:5},
        {id:93, item:'Large Hot Sake', price:"$8",type:'sake',description:'', restaurant_id:5},
        {id:94, item:'Bartender’s Choice Cocktail', price:"$8",type:'cocktail',description:'', restaurant_id:5},
        {id:95, item:'Sangria', price:"$8",type:'cocktail',description:'', restaurant_id:5},
        {id:96, item:'Menu Handrolls', price:"$4",type:'food',description:'', restaurant_id:5},
        {id:97, item:'Agedashi Tofu', price:"$5",type:'food',description:'', restaurant_id:5},
        {id:98, item:'Crispy Brussles', price:"$5",type:'food',description:'', restaurant_id:5},
        {id:99, item:'Kurobuta Pork Belly', price:"$7",type:'food',description:'', restaurant_id:5},
        {id:100, item:'Shishito Peppers', price:"$7",type:'food',description:'', restaurant_id:5},
        {id:101, item:'4pc Hamachi Jalapeno', price:"$10",type:'food',description:'', restaurant_id:5},
        {id:102, item:'Homemade Pork & Chicken Gyoza', price:"$10",type:'food',description:'', restaurant_id:5},
        {id:103, item:'Pork & Shrimp Shumai with Spicy Mustard', price:"$10",type:'food',description:'', restaurant_id:5},
        ///THE RIO
        {id:104, item:'THE CLASSIC RIO MARG', price:"",type:'cocktail',description:'The legendary mixture of tequila, salt and lime, makes the world a better place. Available on the rocks or frozen. Mango | Strawberry | Manberry', restaurant_id:6},
        {id:105, item:'BIG TEX MARG', price:"",type:'cocktail',description:'Cuervo tradicional silver, orange liqueur, fresh citrus', restaurant_id:6},
        {id:106, item:'BARREL-AGED BIG TEX', price:"",type:'cocktail',description:'Ask your server for our featured barrel-aged tequila', restaurant_id:6},
        {id:107, item:'SELECT DRAFTS', price:"$3",type:'beer',description:'', restaurant_id:6},
        {id:108, item:'SELECT CANS', price:"$3",type:'beer',description:'', restaurant_id:6},
        {id:109, item:'WINE', price:"$5",type:'wine',description:'', restaurant_id:6},
        {id:110, item:'CHICHARRÓNES & SALSA', price:"",type:'food',description:'Choose any three salsas: classic green, salsa morita, smoky tomatillo, atómica, avocado salsa', restaurant_id:6},
        {id:111, item:'BAJA FISH', price:"",type:'food',description:'Corn tortilla, cabbage, Mexican-style crema, Valentina™ hot sauce', restaurant_id:6},
        {id:112, item:'GREEN CHILE QUESO', price:"",type:'food',description:'Blend of chile con queso and house-made green chile Try w/ house-made chorizo', restaurant_id:6},
        {id:113, item:'SHISHITO RELLENO', price:"",type:'food',description:'Corn tortilla, fried cheese, shishito peppers, classic green salsa', restaurant_id:6},
        {id:114, item:'CRISPY JALAPEÑO CAPS', price:"",type:'food',description:'Fried jalapeños, poblano ranch dipping sauce, fresh-cut veggies', restaurant_id:6},
        {id:115, item:'GRILLED STEAK', price:"",type:'food',description:'Flour tortilla, smoky tomatillo salsa, onion, cilantro, lime', restaurant_id:6},
        {id:116, item:'B.A.P. CARNITAS NACHOS', price:"",type:'food',description:'Big-A$$ plate of nachos to get the party started Black beans, jack, pico de gallo, carnitas, Mexican-style crema, bbq sauce escabeche', restaurant_id:6},
        {id:117, item:'CILANTRO-LIME GRILLED CHICKEN', price:"",type:'food',description:'Flour tortilla, avocado salsa, onion, cilantro, lime', restaurant_id:6},
        {id:118, item:'BEER-BRAISED CARNITAS', price:"",type:'food',description:'Corn tortilla, smoky tomatillo salsa, pickled onion, cilantro', restaurant_id:6},
        //MOUNTAIN SUN
        {id:119, item:'House Pint', price:"$5",type:'beer',description:'', restaurant_id:7},
        {id:120, item:'Margarita', price:"$5",type:'cocktail',description:'', restaurant_id:7},
        {id:121, item:'Pizza', price:"$5",type:'food',description:'', restaurant_id:7},
        //SANTO
        {id:122, item:'Chips and Salsa', price:"$2",type:'food',description:'piña, verde, mexicana', restaurant_id:8},
        {id:123, item:'modelo especial, pacifico ', price:"$",type:'beer',description:'add a shot of tequila +3', restaurant_id:8},
        {id:124, item:'green chile cheese fries', price:"$6",type:'food',description:'', restaurant_id:8},
        {id:125, item:'house margarita', price:"$7",type:'cocktail',description:'100% blue weber agave, grove street alchemy orange liqueur, simple, lime', restaurant_id:8},
        {id:126, item:'frito pie', price:"$7",type:'food',description:'fritos, beef chile, house cheese blend, crema Mexican, green onion add avocado +2 add sunny side egg +2', restaurant_id:8},
        ///MATEO HAS NO ONLINE MENU

        ///AVANTI N/A

        //ROSETA
        {id:127, item:'Select Cocktails', price:"$6",type:'cocktails',description:'', restaurant_id:11},
        {id:128, item:'Wine', price:"$5",type:'wine',description:'', restaurant_id:11},
        {id:129, item:'Select Beers', price:"$4",type:'beer',description:'', restaurant_id:11},
        ///WEST END
        {id:130, item:'W.E.T Fries', price:"$6",type:'food',description:'house fries, cheesy sauce, bacon, scallions', restaurant_id:12},
        {id:131, item:'Happy Hour Burger', price:"$7",type:'food',description:'tavern burger, aioli, lettuce, onions, tomatos', restaurant_id:12},
        {id:132, item:'Well Liquor', price:"$6",type:'shot',description:'', restaurant_id:12},
        {id:133, item:'Post Draft Beer', price:"$5",type:'beer',description:'top rope lager || know filter ipa || howdy pilsner', restaurant_id:12},
        {id:134, item:'Old Fashioned', price:"$8",type:'cocktail',description:'', restaurant_id:12},
        {id:135, item:'Margarita', price:"$8",type:'cocktail',description:'', restaurant_id:12},
        {id:136, item:'Manhattan', price:"$8",type:'cocktail',description:'', restaurant_id:12},
        //NEXT DOOR
        {id:137, item:'Margarita', price:"$5",type:'cocktail',description:'el jimador blanco tequila, lime, agave, lemon,orange', restaurant_id:14},
        {id:138, item:'Monty Cold Snack Lager', price:"$2",type:'beer',description:'', restaurant_id:14},
        {id:139, item:'Avery IPA Pitcher', price:"$10",type:'beer',description:'', restaurant_id:14},
        {id:140, item:'5-Pack Chicken Tinga Street Tacos', price:"$",type:'food',description:'chipotle, cilantro, onion, queso fresco (gf)', restaurant_id:14},
        {id:141, item:'5-Pack Cheeseburger Sliders', price:"$10",type:'food',description:'tillamook cheddar, pickles, onions, dijon-mayo, sweet roll', restaurant_id:14},
        {id:142, item:'5-pack Nashville hot Fried Chicken Sliders', price:"$10",type:'food',description:'pickles, duke’s mayo, sweet roll', restaurant_id:14},
        ///CENTRO
        {id:143, item:'GUACAMOLE', price:"$6",type:'food',description:'corn torilla chips', restaurant_id:15},
        {id:144, item:'GUACAMOLE DELUXE', price:"$8",type:'food',description:'fried plantains, pickled fresno, crispy chickpeas, semilla salsa, corn tortilla chips', restaurant_id:15},
        {id:145, item:'QUESO', price:"$7",type:'food',description:'roasted chiles, crispy shallots, tortillas, chips add chorizo verde +4', restaurant_id:15},
        {id:146, item:'NACHOS', price:"$8",type:'food',description:'charro beans, queso fundido, pico de gallo, pickled onion, green olive, crema add chicken, beef, pork carnitas or cauliflower +4', restaurant_id:15},
        {id:147, item:'BAJA SHRIMP COCKTAIL', price:"$7",type:'food',description:'tomato, red onion, serrano chile, lime, cilantro, avocado, corn tortilla chips, saladitas crackers', restaurant_id:15},
        {id:148, item:'CRISPY CAULIFLOWER', price:"$6",type:'food',description:'cauliflower puree, xnipec sauce, za’atar, pickled fresno, golden raisins, dill', restaurant_id:15},
        {id:149, item:'PICANTE CHICKEN THIGH FRY MISTO', price:"$7",type:'food',description:'green olive, cactus, lime, cilantro, creamy jalapeño crema', restaurant_id:15},
        {id:150, item:'THE GROOVY', price:"$5",type:'food',description:'black lentil, barley, roasted peppers, radish, avocado, chipotle crema', restaurant_id:15},
        {id:151, item:'POLLO LOCO', price:"$6",type:'food',description:'grilled chicken, garlic mojo, pickled onions, cilantro', restaurant_id:15},
        {id:152, item:'ALOHA', price:"$7",type:'food',description:'pork carnitas, grilled pineapple, green onion', restaurant_id:15},
        {id:153, item:'COIN STYLE MARGARITA silver', price:"$5",type:'cocktail',description:'monte alban, triple sec, lime', restaurant_id:15},
        {id:154, item:'COIN STYLE MARGARITA reposado', price:"$6",type:'cocktail',description:'monte alban, triple sec, lime', restaurant_id:15},
        {id:155, item:'COIN STYLE MARGARITA añejo', price:"$7",type:'cocktail',description:'monte alban, triple sec, lime', restaurant_id:15},
        {id:156, item:'MOJITO', price:"$7",type:'cocktail',description:'cane run rum, mint, fresh-squeezed lime, soda', restaurant_id:15},
        {id:157, item:'DARK & STORMY', price:"$6",type:'cocktail',description:'goslings black seal rum, ginger beer, fresh-squeezed lime', restaurant_id:15},
        {id:158, item:'SANGRIA', price:"$7",type:'cocktail',description:'brandy, gin, fresh-squeezed juice, berries, herbs, spices choice of red, white, or rosé wine', restaurant_id:15},
        {id:159, item:'MARGARITA JELLO SHOTS', price:"$2",type:'shot',description:'', restaurant_id:15},
        {id:160, item:'POST CAN', price:"$4",type:'beer',description:'howdy western pilsner', restaurant_id:15},
        {id:161, item:'DRAFT BEER', price:"$4",type:'beer',description:'top rope mexican-style lager or ‘el corn’ dark lager', restaurant_id:15},
        {id:162, item:'HOUSE WINE', price:"$5",type:'wine',description:'red or white', restaurant_id:15},
        {id:163, item:'AFTER WORK SPECIAL', price:"$",type:'',description:'top rope mexican lager with choice: monte alban silver/lime/salt OR monte alban reposado/orange/cinnamon banhez mezcal & grapefruit & sugar +1 | old forester bourbon & orange & cherry +1', restaurant_id:15},
      ]);
    });
};
