
exports.seed = function(knex) {
  // Deletes ALL existing entries
  //return knex('menu').truncate()
    //.then(function () {
      // Inserts seed entries
      return knex('menu').insert([
        //TEST LINE
        //{id: 777777, item: 'MENU2', price: '$7',type: 'cocktail',description: 'Bourbon, elderflower, lemon, ginger ale', restaurant_id:1},    
        //JUNGLE
        {id:164, item:'Dadobier', price:"$4",type:'beer',description:'', restaurant_id:16},
        {id:165, item:'Wine', price:"$6",type:'wine',description:'', restaurant_id:16},
        {id:166, item:'', price:"$8",type:'',description:'cocktail', restaurant_id:16},
        {id:167, item:'PINA COLADA', price:"$8",type:'',description:'Gold Rum , Pineapple & Coconut Cream Add Strawberry +$2', restaurant_id:16},
        
        {id:168, item:'IRON RANGER', price:"$8",type:'cocktail',description:'Bonded Bourbon , Pineapple, Lemon, Falernum & Angostura Bitters ', restaurant_id:16},
        {id:169, item:'BLUE HAWAII', price:"$8",type:'cocktail',description:'Vodka, Coconut, Lemon, Pineapple & Blue Curacao ', restaurant_id:16},
        {id:170, item:'MAI TAI', price:"$8",type:'cocktail',description:'Jungle Rum Blend, Curaçao, Lime & Orgeat', restaurant_id:16},
        {id:171, item:'SATURN', price:"$8",type:'cocktail',description:'Gin, Passion Fruit, Orgeat, Falernum & Lime', restaurant_id:16},
        {id:172, item:'PAINKILLER', price:"$8",type:'cocktail',description:'Pusser’s Rum , Pineapple, Orange, Coconut & Nutmeg Choose a Level Level 1: Low ABV Level 2: The Classic Level 3: Float +$2', restaurant_id:16},
        {id:173, item:'MOJITO', price:"$8",type:'cocktail',description:'White Rum, Mint, Lime & Soda', restaurant_id:16},
        {id:174, item:'JUNGLE BIRD', price:"$8",type:'cocktail',description:'Jungle Rum Blend, Pineapple, Campari & Lime', restaurant_id:16},
        {id:175, item:'ZOMBIE', price:"$8",type:'cocktail',description:'Rum, Rhum, Ron, Falernum, Ruby Grapefruit & Lime (Limit 1 per Person)' , restaurant_id:16},
        {id:176, item:'SINGAPORE SLING', price:"$8",type:'cocktail',description:'Gin, Benedictine, Pineapple, Cherry & Soda', restaurant_id:16},
        //JAX
        {id:177, item:'EMERSUM OYSTER', price:"$2",type:'food',description:'house selected east coast oysters on the half shell', restaurant_id:17},
        {id:178, item:'FRIED TOWN DOCK CALAMARI', price:"$9",type:'food',description:'mango-chile mojo, lime aioli', restaurant_id:17},
        {id:179, item:'CUP OF GUMBO', price:"$5",type:'food',description:'louisiana crawfish and local smoked andouille sausage', restaurant_id:17},
        {id:180, item:'GUMBO FRIES', price:"$6",type:'food',description:'house cut french fries, cheddar cheese, smothered with crawfish and andouille sausage gumbo', restaurant_id:17},
        {id:190, item:"1/2 LB. PEEL N’ EAT SHRIMP", price:"$10",type:'food',description:'cocktail and jax mustard sauce', restaurant_id:17},
        {id:191, item:'HOOK SAMPLER', price:"$45",type:'food',description:"1⁄2# peel n’ eat shrimp, 6 emersum oysters, 1⁄2# snow crab", restaurant_id:17},
        {id:192, item:'1 LB. STEAMED PEI MUSSELS', price:"$13",type:'food',description:'classic & delicious ~ chardonnay, garlic & shallot confit, parsley, butter with grilled sourdough', restaurant_id:17},
        {id:193, item:"JAX PO’BOY - SHRIMP OR OYSTER", price:"$12",type:'food',description:'crispy fried shrimp or oysters, lettuce, tomato, pickled mustard seed remoulade, french roll', restaurant_id:17},
        {id:194, item:'BAKED LOBSTER MAC', price:"$12",type:'food',description:'', restaurant_id:17},
        {id:195, item:'HUSHPUPPIES', price:"$4",type:'food',description:'', restaurant_id:17},
        {id:196, item:'HOUSE CUT FRENCH FRIES', price:"$4",type:'food',description:'', restaurant_id:17},
        {id:197, item:'JAX STRAWBERRY LEMONADE', price:"$5",type:'cocktail',description:'strawberry infused vodka, strawberry puree, lemon', restaurant_id:17},
        {id:198, item:'CUCUMBER LEMON PRESS', price:"$5",type:'cocktail',description:'cucumber infused vodka, lemon, soda water', restaurant_id:17},
        {id:199, item:'ICE COLD INFUSION MARTINIS', price:"$6",type:'cocktail',description:'', restaurant_id:17},
        {id:200, item:'RED TREE', price:"$7",type:'wine',description:'PINOT NOIR california', restaurant_id:17},
        {id:201, item:'DARK HORSE ROSE', price:"7",type:'wine',description:'GRENACHE, california', restaurant_id:17},
        {id:203, item:'HESS ‘SHIRTTAIL', price:"$",type:'wine',description:'chardonnay, ca', restaurant_id:17},
        {id:204, item:'DOMAINE ST. MICHELLE BRUT', price:"$7",type:'wine',description:'columbia valley, wa', restaurant_id:17},
        ///FELIX
        {id:206, item:'Chicharrones', price:"$3",type:'food',description:'', restaurant_id:18},
        {id:207, item:'Empanada De Cochinita', price:"$3",type:'food',description:'una empanada, slow-braised yucatecan pork, guacamole fresco, mango-pina salso, plantain fritters', restaurant_id:18},
        {id:208, item:'Pollo Rostizado Taco', price:"$3",type:'food',description:'colorado organic chicken, queso trio, citrus cabbage, pico de gallo, sillantro, corn tortilla', restaurant_id:18},
        {id:209, item:'Al Pastor Portobello Taco', price:"$3",type:'food',description:'diced protobello adobado, carmelized onion, mango-pina salsa, red radish, cilantro, cotija cheese, cilatro corn tortilla', restaurant_id:18},
        {id:210, item:'Salsa Trio With Chips', price:"$7",type:'food',description:'housemade goddess hibiscus chips served with salsa rojo, salsa verde, mango-pina salsa', restaurant_id:18},
        {id:211, item:"My Neighbor's Nachos", price:"$9",type:'food',description:'house-made godess hibiscus chips, chile verde picante, smoky black beans, pico de gallo, ranchero cheese, cilantro crema, jalapeno, fresno chiles, cotija chese, adobo sauce, cilantro', restaurant_id:18},
        {id:212, item:'Signature Margarita', price:"$6",type:'cocktail',description:'el jimador, fresh lime juice, fresh orange juice, sweet and sour, triple sec, agave nectar', restaurant_id:18},
        {id:213, item:'Hibiscus Margarita', price:"$7",type:'cocktail',description:'el jimador infused hibiscus tequila, fresh lime juice, pineapple', restaurant_id:18},
        {id:214, item:'Mango Sunrise Margarita', price:"$7",type:'cocktail',description:'el jimador, mango, fresh lime juice, fresh orange juice, sweet and sour, triple sec, agave nectar, hibiscus crystals', restaurant_id:18},
        {id:215, item:'Watermelon Margarita', price:"$7",type:'cocktail',description:'el jimador, watermelon puree, fresh lime juice, fresh orange juice, sweet and sour, triple sec, agave nectar', restaurant_id:18},
        {id:216, item:'Strawberry-Banana Margarita', price:"$7",type:'cocktail',description:'el jimador blanco tequila, fresh lime juice, strawberry-banana', restaurant_id:18},
        {id:217, item:'Mojito', price:"$7",type:'cocktail',description:'captian morgan white rum, lime juice, simple syrup, mint, soda water', restaurant_id:18},
        {id:218, item:'Select Spritz', price:"$7",type:'cocktail',description:'prosecco, aperitivo select, club soda', restaurant_id:18},
        {id:219, item:'Alamos', price:"$6",type:'wine',description:'cabernet sauvignon', restaurant_id:18},
        {id:220, item:'Proverb', price:"$6",type:'wine',description:'sauvignon blanc', restaurant_id:18},
        {id:221, item:'Coors', price:"$3",type:'beer',description:'', restaurant_id:18},
        {id:222, item:'Coors Light', price:"$3",type:'beer',description:'', restaurant_id:18},
        {id:223, item:'1858 IPA', price:"$4",type:'beer',description:'', restaurant_id:18},
        {id:224, item:'Que Pasa Lager', price:"$4",type:'beer',description:'', restaurant_id:18},
        {id:225, item:'Peach Buzz Blonde Ale', price:"$4",type:'beer',description:'', restaurant_id:18},
        ///CORNER BAR
        {id:226, item:'Southwest Tomato Soup', price:"$6",type:'food',description:'(v) (gf)', restaurant_id:19},
        {id:227, item:'House-Smoked Buffalo Wings', price:"$8",type:'food',description:'8 bone-in wings, signature Buffalo sauce, sliced fresh jalapeños, blue cheese dipping sauce (gf)', restaurant_id:19},
        {id:228, item:'Truffle Fries', price:"$5",type:'food',description:'Truffle aioli, parmesan cheese, herbs (gf)', restaurant_id:19},
        {id:229, item:'Calamari', price:"$0",type:'food',description:'Crispy fried, fresh dill, lemon zest, roasted almonds, crispy garlic chips, bistro dipping sauce (gf)', restaurant_id:19},
        {id:230, item:'Crispy Brussels Sprouts & Cauliflower', price:"$6",type:'food',description:'Chille-soy glaze (v) (gf)', restaurant_id:19},
        {id:231, item:'Draft Beer', price:"$4",type:'beer',description:'', restaurant_id:19},
        {id:232, item:'Sangria', price:"$7",type:'cocktail',description:'Fruit-infused spiked Douglas Hill wine. Freshly made.', restaurant_id:19},
        {id:233, item:'Berry Honey Lemonade', price:"$7",type:'cocktail',description:'Berry-Infused Breckenridge vodka, lemon, honey', restaurant_id:19},
        {id:234, item:'Simple Margarita', price:"$8",type:'cocktail',description:'Exotico Silver tequila, agave, fresh lime juice', restaurant_id:19},
        {id:235, item:'The Boulder Mule', price:"$8",type:'cocktail',description:'Deep Eddy Vodka, St. George Spiced Pear Liqueur, ginger beer, lemon', restaurant_id:19},
        {id:236, item:'Bourbon Peach Mule', price:"$8",type:'cocktail',description:'Bird Dog Peach Flavored Whiskey, mint, ginger beer, bitters, lime', restaurant_id:19},
        {id:237, item:'Douglass Hill, Cabernet Sauvignon', price:"$5",type:'wine',description:'', restaurant_id:19},
        {id:238, item:'Murphy-Goode, Pinot Noir', price:"$7",type:'wine',description:'', restaurant_id:19},
        {id:239, item:'BR Cohn Silver Label, Cabernet Sauvignon', price:"$11",type:'wine',description:'', restaurant_id:19},
        {id:240, item:'Piattelli Vineyards Reserve, Malbec, Mendoza', price:"$8",type:'wine',description:'', restaurant_id:19},
        {id:241, item:'Benziger Family Winery, Cabernet Sauvignon', price:"$8",type:'wine',description:'', restaurant_id:19},
        {id:242, item:'Douglass Hill, Chardonnay', price:"$5",type:'wine',description:'', restaurant_id:19},
        {id:243, item:'Stellina di Notte, Prosecco', price:"$6",type:'wine',description:'', restaurant_id:19},
        {id:244, item:'Lafite Rothschild "Aussiéres", Chardonnay', price:"$9",type:'wine',description:'', restaurant_id:19},
        {id:245, item:'Decoy by Duckhorn, Chardonnay', price:"$11",type:'wine',description:'', restaurant_id:19},
        {id:246, item:'La Fiera, Pinot Grigio', price:"$7",type:'wine',description:'', restaurant_id:19},
        {id:247, item:'Fabre en Provence, Dry Rosé', price:"$8",type:'wine',description:'', restaurant_id:19},
        {id:249, item:'Kim Crawford, Sauvignon Blanc', price:"$9",type:'wine',description:'', restaurant_id:19},
        ///THE SINK
        {id:250, item:'All Apatizers', price:"$2 off",type:'food',description:'', restaurant_id:20},
        {id:251, item:'Wine', price:"$2 off",type:'wine',description:'', restaurant_id:20},
        {id:252, item:'Draft and Canend Beer', price:"$2 0ff",type:'beer',description:'', restaurant_id:20},
        {id:253, item:'Signature Cocktails', price:"$2 0ff",type:'cocktail',description:'', restaurant_id:20},
        {id:254, item:'Call, Premium, and Top-shelf Spirits', price:"$2 0ff",type:'shots',description:'', restaurant_id:20},
        {id:255, item:'Mocktails', price:"$2 0ff",type:'NA',description:'', restaurant_id:20},
        {id:256, item:'All West Flanders Draft Beer', price:"$4",type:'beer',description:'', restaurant_id:20},
        ///JILLS
        {id:257, item:'Draft Beers', price:"$6",type:'beer',description:'Ratio IPA, Odell 90 shilling, Wibby Vienna Lager, Bootstrap Lushpuppy IPA', restaurant_id:22},
        {id:258, item:'The Pearl Martini', price:"$9",type:'cocktail',description:'ketel One Botanicals Cucumber and Mint Vodka, elderflower juiced cucumber, lemon', restaurant_id:22},
        {id:259, item:'Blood Orange Paloma', price:"$9",type:'cocktail',description:'Herradura blanco tequila, Giffard pampelmousse, Sicilian blood orange, soda', restaurant_id:22},
        {id:260, item:'Whispering Angel Froze', price:"$9",type:'cocktail',description:'Belvedere vodka, fresh strawberry, citrus', restaurant_id:22},
        {id:261, item:'Negroni Friullano', price:"$9",type:'cocktail',description:"Leoplod's Gin, Amaro Nonino, Campari, Carpano Antica vermouth, Reagans orange bitters", restaurant_id:22},
        {id:262, item:'La Marca, Prosecco', price:"$7",type:'wine',description:'Veneto, Italy', restaurant_id:22},
        {id:263, item:'Domaine Carneros', price:"$12",type:'wine',description:'Napa Valley, CA', restaurant_id:22},
        {id:264, item:'Veuve Cliquot, Yellow Label', price:"$15",type:'wine',description:'Reims, France', restaurant_id:22},
        {id:265, item:'St Julien House, Canyon Road, Chardonnay', price:"$6",type:'wine',description:'CA', restaurant_id:22},
        {id:266, item:'Whispering Angel', price:"$10",type:'wine',description:'Provence, France', restaurant_id:22},
        {id:267, item:'Sonoma-Cutrer, Russian River Ranches', price:"$",type:'wine',description:'Sonoma County, CA', restaurant_id:22},
        {id:268, item:'Domaine Schlumberger, Pino Blanc', price:"$9",type:'wine',description:'Alsace, France', restaurant_id:22},
        {id:269, item:'Van Duzer, Pino Gris', price:"$8",type:'wine',description:'Willamette Valley, OR', restaurant_id:22},
        {id:270, item:'Masi Masianico, Pino Grigio', price:"$7",type:'wine',description:'Friuli, Italy', restaurant_id:22},
        {id:271, item:'Matua, Sauvignon Blanc ', price:"$8",type:'wine',description:'Marlborough, AZ', restaurant_id:22},
        {id:272, item:'Etude, Pinot Nior', price:"$14",type:'wine',description:'Caneros, CA', restaurant_id:22},
        {id:273, item:'Argiano, Super Tuscan', price:"$8",type:'wine',description:'Italy', restaurant_id:22},
        {id:274, item:'Conundrum, Blend', price:"$11",type:'wine',description:'Napa Valley, CA', restaurant_id:22},
        {id:275, item:'St Julien House, Canyon Road, Merlot', price:"$6",type:'wine',description:'CA', restaurant_id:22},
        {id:276, item:'Faustino, La Rioja', price:"$7",type:'wine',description:'Tempranillo, Spain', restaurant_id:22},
        {id:277, item:'St Julien House, Canyon Road< Cabernet Sauvignon', price:"$6",type:'wine',description:'CA', restaurant_id:22},
        {id:278, item:'Terrazas, Malbec', price:"$7",type:'wine',description:'Mendoza, Argentina', restaurant_id:22},
        {id:279, item:'DAOU, Cabernet Sauvignon', price:"$12",type:'wine',description:'Paso Robles, CA', restaurant_id:22},
        {id:280, item:'Mauritson Wines, Zinfandel', price:"$8",type:'wine',description:'Sonoma County, CA', restaurant_id:22},
        {id:281, item:'Prosciutto & Ricotta', price:"$15",type:'food',description:'Biellese NYC molasses-cured prosciutto, ricotta impastata, pistachios, medjool dates & agrumato', restaurant_id:22},
        {id:282, item:"Shrimp and Gayla's Grits", price:"$12",type:'food',description:'Colorado hillbilly ham, andouille, fennel ragout, basil oil', restaurant_id:22},
        {id:283, item:'Tuna au Poivre BLT', price:"$14",type:'food',description:'Ahi Tuna, spicy aioli, smoked bacon, lettuce, tomato & ciabattini', restaurant_id:22},
        {id:284, item:"Jill's Bistro Tots", price:"$7",type:'food',description:'Truffle aioli, Reffiano cheese', restaurant_id:22},
        {id:285, item:'Crispy Brussles', price:"$9",type:'food',description:'Local honey, sea salt & chili flake', restaurant_id:22},
        {id:286, item:'Mediterranean Hummas', price:"$10",type:'food',description:'olives, cucumber, grape tomato, feta & wood oven naan bread', restaurant_id:22},
        {id:287, item:'Korean Hot & Sour Wings', price:"$11",type:'food',description:'Breaded chicken wings, ginger, garlic, gochujang', restaurant_id:22},
        {id:288, item:'Margherita Pizza', price:"$11",type:'food',description:'Tomato sauce, basil, fresh mozzarella ', restaurant_id:22},
        {id:289, item:'Classic Grilled Cheese & Tomato Soup', price:"$11",type:'food',description:'Muenster, provolone, sharp chedder on apline French bread', restaurant_id:22},
        {id:290, item:'The St J Burger', price:"$12",type:'food',description:'1/2 lb. natural beef patty, caramelized onions, chedder, stone ground mustard aoli, lettuce, tomato', restaurant_id:22},
        ///POST CH&WAFF
        {id:291, item:'POST CHICKEN WINGS', price:"6 for $10 | 12 for $18",type:'food',description:'tossed w/ buffalo sauce, bbq or Post dry rub w/ ranch or blue cheese', restaurant_id:23},
        {id:292, item:'BRUSSELS SPROUTS', price:"$5",type:'food',description:'pepper relish, garlic, cotija (v)', restaurant_id:23},
        {id:293, item:'DEVILED EGGS', price:"2 for $5",type:'food',description:'crispy chicken skin, horseradish louie, celery', restaurant_id:23},
        {id:294, item:'CRISPY THIGH FRIES', price:"$7",type:'food',description:'buttermilk marinated fried chicken thigh strips w/ curry ketchup and beer mustard', restaurant_id:23},
        {id:295, item:'CHICKEN TENDERS', price:"3 for $10",type:'food',description:'w/ ranch and beer mustard', restaurant_id:23},
        {id:296, item:'THE POST FAMOUS CHEESEBURGER', price:"$10",type:'food',description:'american cheese, bacon-onion marmalade, special sauce, griddled english muffin', restaurant_id:23},
        {id:297, item:'GET HAPPY SAMPLER FOR 2 OR 4 PEOPLE', price:"$16 | $30",type:'food',description:'deviled eggs, wings, tenders, brussels w/ curry ketchup, beer mustard, ranch', restaurant_id:23},
        {id:298, item:'POST CORE DRAFT BEERS', price:"$5",type:'beer',description:'', restaurant_id:23},
        {id:299, item:'WINE BY THE GLASS', price:"$5",type:'wine',description:'red, white, or bubbly', restaurant_id:23},
        {id:300, item:'MOSCOW MULE', price:"$8",type:'cocktail',description:'vodka, ginger beer, lime juice', restaurant_id:23},
        {id:301, item:'HOUSE MARGARITA', price:"$8",type:'cocktail',description:'', restaurant_id:23},
        {id:302, item:'CROWLERS TO-GO', price:"$8",type:'beer',description:'', restaurant_id:23},
        //// BOTH PETES
        {id:303, item:'House & Coin-style Margaritas', price:"$1 off",type:'cocktail',description:'', restaurant_id:24},
        {id:304, item:'All Draft Beer', price:"$1 off",type:'beer',description:'', restaurant_id:24},
        {id:305, item:'Party Margs', price:"$20",type:'cocktail',description:'', restaurant_id:24},
        {id:306, item:'Large Chips & Queso or Guac', price:"$1 off",type:'food',description:'', restaurant_id:24},
        ////
        {id:307, item:'House & Coin-style Margaritas', price:"$1 off",type:'cocktail',description:'', restaurant_id:25},
        {id:308, item:'All Draft Beer', price:"$1 off",type:'beer',description:'', restaurant_id:25},
        {id:309, item:'Party Margs', price:"$20",type:'cocktail',description:'', restaurant_id:25},
        {id:310, item:'Large Chips & Queso or Guac', price:"$1 off",type:'food',description:'', restaurant_id:25},
        ///ROADHOUSE
        {id:311, item:'Coors Light', price:"14 oz $4 | 25oz $8",type:'beer',description:'', restaurant_id:26},
        {id:312, item:'Wild Cider Roatating', price:"14oz $7.5 | 25oz $12.5",type:'beer',description:'', restaurant_id:26},
        {id:313, item:'Rotating Nitro Ale', price:"14oz $7.5 | 25oz $12.5",type:'beer',description:'', restaurant_id:26},
        {id:314, item:'Odell Myrcenary Double IPA', price:"14oz $9.5",type:'beer',description:'', restaurant_id:26},
        {id:315, item:'All Other Drafts', price:"14oz $5.5 | 25oz $8.5",type:'beer',description:'', restaurant_id:26},
        {id:316, item:'All American Mule', price:"$9",type:'cocktail',description:'Tito’s Handmade Vodka/ginger beer/lime', restaurant_id:26},
        {id:317, item:'Peach Mule', price:"$9",type:'cocktail',description:'Belvedere Peach Vodka/ginger beer/lemon', restaurant_id:26},
        {id:318, item:'Aperol Spritz', price:"$9",type:'cocktail',description:'Aperol/prosecco/mint', restaurant_id:26},
        {id:319, item:'Depot Margarita', price:"$9",type:'cocktail',description:'Herradura Blanco Tequila/ triple sec/lime/agave', restaurant_id:26},
        {id:320, item:'Premium Cocktails', price:"$6",type:'cocktail',description:'Jack Daniel’s / Jack Daniel’s Rye / Jack Daniel’s Honey / Jack Daniel’s Fire / Deep Eddy Vodka Flavors: / Grapefruit/Orange/Lemon/Regular', restaurant_id:26},
        {id:323, item:'All Well Drinks', price:"$5",type:'cocktail',description:'', restaurant_id:26},
        {id:324, item:'House Wine', price:"6oz $5 | 9oz $7",type:'wine',description:'Canyon Road Pinot Grigio / Canyon Road Chardonnay / Canyon Road Merlot / Canyon Road Cabernet ', restaurant_id:26},
        {id:325, item:'Chips and Guacamole', price:"$6",type:'food',description:'lime/cilantro/cotija cheese', restaurant_id:26},
        {id:326, item:'One Chorizo Taco', price:"$4",type:'food',description:'flour tortilla/chorizo/pico de gallo/avocado crema', restaurant_id:26},
        {id:327, item:'Chef’s Dip', price:"$6",type:'food',description:'homemade ranch potato chips/our twist on a classic French onion dip', restaurant_id:26},
        {id:328, item:'One Blackened Fish Taco', price:"$5",type:'food',description:'flour tortilla/blackened white fish/mango salsa/apple-chipotle slaw/shaved radish', restaurant_id:26},
        {id:329, item:'Brussels Sprouts', price:"$7",type:'food',description:'sweet & spicy sesame/goat cheese', restaurant_id:26},
        {id:330, item:'Pretzels & Queso', price:"$7",type:'food',description:'queso blend/pico de gallo/warm pretzel bites', restaurant_id:26},
        {id:331, item:'Nachos', price:"$10",type:'food',description:'corn tortilla chips/queso/avocado lime crema/tomatoes/shaved radish/shaved jalapeño/cilantro', restaurant_id:26},
        {id:332, item:'Margherita', price:"$10",type:'food',description:'crushed-tomato sauce/provolone/buffalo mozzarella/fresh basil/tomato', restaurant_id:26},
        {id:333, item:'Truffled Mushroom', price:"$12",type:'food',description:'garlic-truffle oil/wild mushrooms/mozzarella/asiago/fresh herbs', restaurant_id:26},
        {id:334, item:'Buffalo Chicken', price:"$12",type:'food',description:'buffalo sauce/mozzarella/chicken/red onion/shredded carrot/celery/choice of ranch or blue cheese', restaurant_id:26},
    ]);
  //});
};
